# Build all containers in this file with: docker compose build
# Launch this file with : docker compose up -d
# Unload this file with : docker compose down -v

services:

    web-app:
    
        build: ./web-app
        
        container_name: web-app
        
        working_dir: /var/www/target
        
        volumes:
            # Map the host logs to the project target logs folder
            - ${PROJECT_TARGET_FOLDER}/logs/docker:/var/log
        
            # Our Project target folder must be specified on the PROJECT_TARGET_FOLDER environment variable.
            # It will be mounted on a custom empty folder (/var/www/target) inside the docker container.
            - ${PROJECT_TARGET_FOLDER}:/var/www/target
            
            # Our Project dist folder must be specified on the PROJECT_DIST_FOLDER environment variable.
            # It will be mounted on the apache root folder (/var/www/html) inside the docker container.
            # This will be used to launch web projects that require a webserver
            - ${PROJECT_DIST_FOLDER}:/var/www/html
                  
        ports:
            - 80:80
            - 443:443
            
        networks:
            - custom-network
  
    database:
  
        image: mariadb:11.7.2
    
        container_name: database
    
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

        ports:
            - 3306:3306
            
        networks:
            - custom-network
        
networks:
    
    custom-network:
        
        driver: bridge